-- Create MVP sponsored ad tracking tables.
-- Public users can write impressions/clicks, but only admins can read or delete
-- tracking data. No service_role key is used by the frontend.

create table if not exists public.ad_impressions (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  ad_id bigint references public.sponsored_posts(id) on delete cascade,
  placement text default 'feed',
  page_path text,
  user_id uuid references auth.users(id) on delete set null,
  session_id text,
  metadata jsonb default '{}'::jsonb
);

create table if not exists public.ad_clicks (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  ad_id bigint references public.sponsored_posts(id) on delete cascade,
  placement text default 'feed',
  page_path text,
  target_url text,
  user_id uuid references auth.users(id) on delete set null,
  session_id text,
  metadata jsonb default '{}'::jsonb
);

create index if not exists ad_impressions_ad_id_created_at_idx
on public.ad_impressions (ad_id, created_at desc);

create index if not exists ad_clicks_ad_id_created_at_idx
on public.ad_clicks (ad_id, created_at desc);

alter table public.ad_impressions enable row level security;
alter table public.ad_clicks enable row level security;

drop policy if exists "Ad impressions public insert" on public.ad_impressions;
drop policy if exists "Ad impressions admins read all" on public.ad_impressions;
drop policy if exists "Ad impressions admins delete all" on public.ad_impressions;
drop policy if exists "Ad clicks public insert" on public.ad_clicks;
drop policy if exists "Ad clicks admins read all" on public.ad_clicks;
drop policy if exists "Ad clicks admins delete all" on public.ad_clicks;

create policy "Ad impressions public insert"
on public.ad_impressions
for insert
to public
with check (true);

create policy "Ad impressions admins read all"
on public.ad_impressions
for select
to authenticated
using (public.is_admin());

create policy "Ad impressions admins delete all"
on public.ad_impressions
for delete
to authenticated
using (public.is_admin());

create policy "Ad clicks public insert"
on public.ad_clicks
for insert
to public
with check (true);

create policy "Ad clicks admins read all"
on public.ad_clicks
for select
to authenticated
using (public.is_admin());

create policy "Ad clicks admins delete all"
on public.ad_clicks
for delete
to authenticated
using (public.is_admin());
