-- Create FoodieFeed self-serve sponsored post placements for MVP.
-- Ads are clearly separated from organic posts in the UI. Only admins can
-- manage sponsored_posts; public users can only read currently active ads.

create table if not exists public.sponsored_posts (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  title text not null,
  brand_name text not null,
  description text,
  image_url text,
  target_url text,
  city text,
  district text,
  category text,
  placement text default 'feed',
  starts_at timestamptz default now(),
  ends_at timestamptz not null,
  is_active boolean default true,
  priority integer default 0
);

create index if not exists sponsored_posts_feed_active_idx
on public.sponsored_posts (placement, is_active, starts_at, ends_at, priority desc, created_at desc);

alter table public.sponsored_posts enable row level security;

drop policy if exists "Sponsored posts public read active" on public.sponsored_posts;
drop policy if exists "Sponsored posts admins read all" on public.sponsored_posts;
drop policy if exists "Sponsored posts admins insert" on public.sponsored_posts;
drop policy if exists "Sponsored posts admins update" on public.sponsored_posts;
drop policy if exists "Sponsored posts admins delete" on public.sponsored_posts;

create policy "Sponsored posts public read active"
on public.sponsored_posts
for select
to public
using (
  is_active = true
  and starts_at <= now()
  and ends_at >= now()
);

create policy "Sponsored posts admins read all"
on public.sponsored_posts
for select
to authenticated
using (public.is_admin());

create policy "Sponsored posts admins insert"
on public.sponsored_posts
for insert
to authenticated
with check (public.is_admin());

create policy "Sponsored posts admins update"
on public.sponsored_posts
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Sponsored posts admins delete"
on public.sponsored_posts
for delete
to authenticated
using (public.is_admin());
