-- Harden post likes with user/session-level de-duplication.
-- posts.likes remains the display counter. post_likes is the source of truth
-- for preventing repeated likes by the same authenticated user or anonymous
-- browser session. metadata size is intentionally not constrained in this MVP.

create table if not exists public.post_likes (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  session_id text,
  metadata jsonb default '{}'::jsonb,
  constraint post_likes_user_or_session_required
    check (user_id is not null or session_id is not null),
  constraint post_likes_session_id_length
    check (session_id is null or char_length(session_id) <= 120)
);

create index if not exists post_likes_post_id_idx
on public.post_likes (post_id);

create index if not exists post_likes_user_id_idx
on public.post_likes (user_id);

create index if not exists post_likes_session_id_idx
on public.post_likes (session_id);

create unique index if not exists post_likes_post_user_unique_idx
on public.post_likes (post_id, user_id)
where user_id is not null;

create unique index if not exists post_likes_post_session_unique_idx
on public.post_likes (post_id, session_id)
where user_id is null and session_id is not null;

alter table public.post_likes enable row level security;

drop policy if exists "Post likes admins read all" on public.post_likes;
drop policy if exists "Post likes admins delete all" on public.post_likes;

create policy "Post likes admins read all"
on public.post_likes
for select
to authenticated
using (public.is_admin());

create policy "Post likes admins delete all"
on public.post_likes
for delete
to authenticated
using (public.is_admin());

drop function if exists public.increment_post_likes(bigint);
drop function if exists public.increment_post_likes(bigint, text, jsonb);

create or replace function public.increment_post_likes(
  post_id bigint,
  session_id text default null,
  metadata jsonb default '{}'::jsonb
)
returns public.posts
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_session_id text := nullif(btrim(increment_post_likes.session_id), '');
  v_metadata jsonb := coalesce(increment_post_likes.metadata, '{}'::jsonb);
  v_post public.posts;
begin
  if not exists (
    select 1
    from public.posts
    where id = increment_post_likes.post_id
  ) then
    raise exception 'post_not_found';
  end if;

  if v_session_id is not null and char_length(v_session_id) > 120 then
    raise exception 'invalid_session_id';
  end if;

  if v_user_id is null and v_session_id is null then
    raise exception 'session_id_required';
  end if;

  begin
    if v_user_id is not null then
      insert into public.post_likes (
        post_id,
        user_id,
        session_id,
        metadata
      )
      values (
        increment_post_likes.post_id,
        v_user_id,
        v_session_id,
        v_metadata
      );
    else
      insert into public.post_likes (
        post_id,
        session_id,
        metadata
      )
      values (
        increment_post_likes.post_id,
        v_session_id,
        v_metadata
      );
    end if;
  exception
    when unique_violation then
      raise exception 'already_liked';
  end;

  update public.posts
  set likes = coalesce(likes, 0) + 1
  where id = increment_post_likes.post_id
  returning * into v_post;

  if v_post.id is null then
    raise exception 'post_not_found';
  end if;

  return v_post;
end;
$$;

revoke all on function public.increment_post_likes(bigint, text, jsonb) from public;
grant execute on function public.increment_post_likes(bigint, text, jsonb) to anon;
grant execute on function public.increment_post_likes(bigint, text, jsonb) to authenticated;
