create table if not exists posts (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null,
  title text not null,
  city text not null,
  district text not null,
  address text not null,
  img text,
  category text default 'other',
  likes integer default 0,
  expiry timestamptz not null
);

create table if not exists comments (
  id bigint generated by default as identity primary key,
  post_id bigint references posts(id) on delete cascade,
  created_at timestamptz default now(),
  user_name text default '訪客',
  content text not null
);
